version: "3.8"

services:
  academia-db:
    image: postgres:17.5
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    

  api:
    image: ghcr.io/${GITHUB_REPOSITORY}:prod
    depends_on:
      - academia-db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - DB_CONNECTION_STRING_FILE=/run/secrets/db_connection_string
    networks:
      - app_network
    secrets:
      - source: db_connection_string
        target: db_connection_string
    deploy:
      replicas: 5
      update_config:
        parallelism: 1
        delay: 30s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
        window: 120s
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M

  nginx:
    image: nginx:1.25.5-alpine
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - app_network
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      resources:
        limits:
          memory: 128M

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: overlay
    attachable: true

secrets:
  db_connection_string:
    name: db_connection_string
    file: ./db_connection_string.txt


configs:
  nginx_config:
    file: ./nginx.conf
